Pennsieve/app-deploy-service

- fargate/app-provisioner/scripts/destroy-infrastructure.sh
- lambda/service/models/application.go
- lambda/service/store_dynamodb/application.go
> fix: fixes for GET and POST

- lambda/service/mappers/mappers.go
- adds applicationType to returned payload for GET /applications
> fix: adds applicationType to returned payload for GET /applications

- fargate/app-provisioner/main.go
- fargate/app-provisioner/provisioner/parser/output.go
- fargate/app-provisioner/provisioner/parser/parser_test.go
- fargate/app-provisioner/provisioner/parser/test-data/outputs_test.json
- fargate/app-provisioner/provisioner/store_dynamodb/application.go
- fargate/app-provisioner/provisioner/store_dynamodb/store_dynamodb.go
- fargate/app-provisioner/terraform/infrastructure/outputs.tf
- lambda/service/handler/delete_application_handler.go
- lambda/service/handler/get_application_handler.go
- lambda/service/handler/get_applications_handler.go
- lambda/service/mappers/mappers.go
- lambda/service/models/application.go
- lambda/service/store_dynamodb/application.go
- adds applicationId
- fixes GET filtering
- adds some debug statements
> fix: adds applicationId

- fargate/app-provisioner/go.mod
- fargate/app-provisioner/go.sum
- fargate/app-provisioner/main.go
- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
- fargate/app-provisioner/provisioner/provisioner.go
- fargate/app-provisioner/provisioner/runner/runner.go
- fargate/app-provisioner/provisioner/runner/task_runner.go
- lambda/service/handler/post_applications_handler.go
- terraform/iam.tf
- invokes deployer: build and deploy on POST
> feature: invokes deployer

- terraform/iam.tf
> fix: updates policy name

- terraform/iam.tf
> fix: updates fargate permissions

- lambda/service/handler/post_applications_handler.go
> fix: updates ENV variable

- lambda/service/handler/post_application_deploy_handler.go
- terraform/variables.tf
-  avail more resources to deployer
> fix: avail more resources to deployer

- terraform/fargate.tf
> fix: apply new resources

- terraform/fargate.tf
- swap resource allocation to fargate supported
> fix resources

- lambda/service/handler/get_applications_handler.go
- lambda/service/store_dynamodb/store_dynamodb.go
- builds filters for GET request
> feature: updates GET request to take filters

- lambda/service/store_dynamodb/store_dynamodb.go
> fix: fixes conditional statement

- fargate/app-provisioner/terraform/infrastructure/ecs.tf
> fix: updates container name

- fargate/app-provisioner/terraform/infrastructure/iam.tf
-  app specific roles and policies
> fix: app specific roles and policies

- fargate/app-provisioner/scripts/infrastructure.sh
- lambda/service/handler/post_applications_handler.go
> fix: debugging resourcing

- lambda/service/handler/post_applications_handler.go
> fix: variable assignment

- fargate/app-provisioner/scripts/infrastructure.sh
> fix: debugging

- fargate/app-provisioner/scripts/infrastructure.sh
> fix: string to int conversion

- fargate/app-provisioner/scripts/infrastructure.sh
> fix: more debugging

- fargate/app-provisioner/terraform/infrastructure/ecs.tf
- test explicit setting of values
> fix: test explicit setting of values

- fargate/app-provisioner/terraform/infrastructure/ecs.tf
> fix: set higher storage value

- fargate/app-provisioner/terraform/infrastructure/ecs.tf
> fix: updates storage

- fargate/app-provisioner/terraform/infrastructure/ecs.tf
> fix: fixes typo

- terraform/variables.tf
- bump up memory to test R deploy
> fix: bump up memory to test R deploy

- fargate/app-provisioner/main.go
- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
- fargate/app-provisioner/provisioner/provisioner.go
- creates an inline policy on the fly
> fix: creates a policy

- terraform/iam.tf
- adds permissions to allow adding a policy
> fix: adds putRolePolicy to role

- terraform/iam.tf
> fix: adds put role policy

- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
> fix: updates malformed doc

- fargate/app-provisioner/main.go
- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
- fargate/app-provisioner/provisioner/provisioner.go
- checks for policy before creation
- moves policy creation to "create"
> fix: checks for policy before creation

- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
> fix: debug statement

- terraform/iam.tf
> fix: adds new permission

- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
> fix: refactors

- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
- wait for policy to be created
> fix: wait for policy to be created

- fargate/app-provisioner/main.go
- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
> fix: creates a client per action

- fargate/app-provisioner/main.go
- fargate/app-provisioner/provisioner/store_dynamodb/application.go
- fargate/app-provisioner/provisioner/store_dynamodb/store_dynamodb.go
- lambda/service/handler/post_applications_handler.go
- lambda/service/models/application.go
- lambda/service/store_dynamodb/application.go
- lambda/service/store_dynamodb/store_dynamodb.go
application registration is now two-phased:
- insert record on POST (status: registering) - params etc
- update record once provisioning complete (status: registered)
> feature: supports params

- fargate/app-provisioner/provisioner/store_dynamodb/store_dynamodb.go
- lambda/service/handler/post_applications_handler.go
- removes reserved word from query
- fixes typo in validation query
> fix: reserved keyword

- fargate/app-provisioner/provisioner/store_dynamodb/application.go
- fargate/app-provisioner/provisioner/store_dynamodb/store_dynamodb.go
- lambda/service/store_dynamodb/application.go
> fix: updates keyword

- fargate/app-provisioner/main.go
- lambda/service/handler/errors.go
- lambda/service/handler/post_applications_handler.go
- updates error handling
- fixes destinationUrl reference
> fix: post endpoint error handling

- lambda/service/handler/get_application_handler.go
- lambda/service/mappers/mappers.go
- surface new fields in GET request
> fix: surface new fields

- terraform/variables.tf
- testing R deployments and they run slow
> fix: updates memory

- terraform/variables.tf
> fix: updates deployer tag

- terraform/fargate.tf
- fixes memory and CPU for container
> fix: memory and CPU for container

- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
- lambda/service/go.mod
- lambda/service/handler/delete_application_handler.go
- lambda/service/handler/post_application_deploy_handler.go
- lambda/service/handler/post_applications_handler.go
- lambda/service/models/application.go
- returns valid json endpoint response
Related: https://app.clickup.com/t/8689bgw9v
> fix: valid json endpoint response

- fargate/app-provisioner/Dockerfile
> fixes build

- lambda/service/handler/errors.go
- refactors error handling function
> fix: refactors handlerError

- fargate/app-provisioner/main.go
- fargate/app-provisioner/provisioner/utils/utils.go
- fargate/app-provisioner/provisioner/utils/utils_test.go
- lambda/service/store_dynamodb/store_dynamodb.go
- updates application slug so that it differs per compute node
> fix: updates app slug

- fargate/app-provisioner/provisioner/utils/utils.go
- fargate/app-provisioner/provisioner/utils/utils_test.go
> fix: shortens slug

- fargate/app-provisioner/scripts/destroy-infrastructure.sh
- fargate/app-provisioner/scripts/infrastructure.sh
- updates the state file location
> fix: updates state location

- fargate/app-provisioner/scripts/destroy-infrastructure.sh
- fargate/app-provisioner/scripts/infrastructure.sh
- fargate/app-provisioner/terraform/infrastructure/ecr.tf
- fargate/app-provisioner/terraform/infrastructure/ecs.tf
- fargate/app-provisioner/terraform/infrastructure/iam.tf
- fargate/app-provisioner/terraform/infrastructure/variables.tf
> fix: adds tags and debugging

- fargate/app-provisioner/main.go
- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
- fargate/app-provisioner/scripts/public-repository.sh
> fix: updates script location

- fargate/app-provisioner/terraform/pennsieve/public-repository/variables.tf
> fix: adds missing variables

- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
- fargate/app-provisioner/scripts/public-repository.sh
- fargate/app-provisioner/terraform/pennsieve/public-repository/ecr.tf
> fix: updates public repo name

- fargate/app-provisioner/terraform/pennsieve/public-repository/variables.tf
> fix: removes variable

- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
- fargate/app-provisioner/scripts/public-repository.sh
- fargate/app-provisioner/terraform/pennsieve/public-repository/ecr.tf
- fargate/app-provisioner/terraform/pennsieve/public-repository/variables.tf
- conform to regex for repo name
> fix: conform to regex

- fargate/app-provisioner/provisioner/parser/output.go
- fargate/app-provisioner/provisioner/parser/parser_test.go
- fargate/app-provisioner/provisioner/parser/test-data/public_ecr_outputs_test.json
- fargate/app-provisioner/terraform/pennsieve/public-repository/ecr.tf
- fargate/app-provisioner/terraform/pennsieve/public-repository/outputs.tf
- terraform/iam.tf
> fix: retrieve ARN

- fargate/app-provisioner/main.go
- updates to push to public repo
> feature: updates to push to public repo

- fargate/app-provisioner/main.go
- terraform/iam.tf
- adds permission to list tags
> fix: permissions

- fargate/app-provisioner/main.go
- fargate/app-provisioner/provisioner/aws/aws_provisioner.go
- fargate/app-provisioner/provisioner/provisioner.go
- gets and passes provisioner credentials
> fix: gets and passes provisioner credentials

- terraform/iam.tf
> fix: adds push permissions

- fargate/app-provisioner/main.go
- updates reference to source tag
> fix: updates reference to source tag

- fargate/app-provisioner/Dockerfile
- terraform/outputs.tf
> fix: adds table outputs
